spring:
  application:
    name: furniture

  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/furniture

  #springboot文件上传相关配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 10000MB

#mybatis相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#阿里云OSS相关配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    backetName: pvzer
    region: cn-beijing

#springboot事务隔离级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
